# -*- coding: utf-8 -*-
"""ACTIVATION_FUNCTIONS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muJrW_ET8s2DxoFfNiQkp4viCdE27kTR
"""

import numpy as np
import matplotlib.pyplot as plt

# Funcion Sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.linspace(-10, 10, 400)
y = sigmoid(x)

plt.figure()
plt.plot(x, y, color='purple', label="Sigmoid", linewidth=.5)
plt.title("SIGMOID ACTIVATION FUNCTION")
plt.xlabel("Entrada(x)")
plt.ylabel("Salida f(sigmoid)")
plt.grid(True)
plt.legend()
plt.show()


# Funcion Tanh
def tanh(x):
    return np.tanh(x)

x = np.linspace(-10, 10, 400)
y = tanh(x)

plt.figure()
plt.plot(x, y, color="orange", label="Tanh", linewidth=.5)
plt.title("TANH ACTIVATION FUNCTION")
plt.xlabel("Entrada (x)")
plt.ylabel("Salida f(tanh(x))")
plt.grid(True)
plt.legend()
plt.show()


# Funcion ReLU
def ReLU(x):
    return np.maximum(0, x)

x = np.linspace(-20, 20, 500)
y = ReLU(x)

plt.figure()
plt.plot(x, y, color="green", label="Tanh", linewidth=.5)
plt.title("RELU ACTIVATION FUNCTION")
plt.xlabel("Entrada (x)")
plt.ylabel("Salida f(ReLU(x))")
plt.grid(True)
plt.legend()
plt.show()


#Funcion Leaky ReLU
def Leaky_ReLU(x):
    return np.where(x > 0, x, 0.01 * x)

x = np.linspace(-10, 10, 500)
y = Leaky_ReLU(x)

plt.figure()
plt.plot(x, y, color='gray', label="Leaky ReLU", linewidth=.5)
plt.title("Función de Activación Leaky ReLU")
plt.xlabel("Entrada(x)")
plt.ylabel("Salida f(LeakyReLU(x))")
plt.grid(True)
plt.legend()
plt.show()


#Funcion Softplus
def softplus(x):
    return np.log(1 + np.exp(x))

x = np.linspace(-10, 10, 400)
y = softplus(x)

plt.figure()
plt.plot(x, y, color='red', label="Softplus", linewidth=.5)
plt.title("Función de Activación Softplus")
plt.xlabel("x")
plt.ylabel("Softplus(x)")
plt.grid(True)
plt.legend()
plt.show()


plt.figure()

plt.plot(x,sigmoid(x),label="Sigmoid")
plt.plot(x,tanh(x),label="Tanh")
plt.plot(x,ReLU(x),label="ReLU")
plt.plot(x,Leaky_ReLU(x),label="Leaky ReLU")
plt.plot(x,softplus(x),label="Softplus")

plt.title("Comparación de Funciones de Activación")
plt.xlabel("x")
plt.ylabel("Salida")
plt.grid(True)
plt.legend()

plt.show()