# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npF4CcrkGo9tM6EhRe8jCqVw7JBSDXM6
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x): return 1 / (1 + np.exp(-x))
def tanh(x): return np.tanh(x)
def relu(x): return np.maximum(0, x)
def leaky_relu(x, alpha=0.01): return np.where(x > 0, x, x * alpha)
def softplus(x): return np.log(1 + np.exp(x))

x = np.linspace(-10, 10, 400)
functions = [
    (sigmoid, "Sigmoid"), (tanh, "Tanh"), (relu, "ReLU"),
    (leaky_relu, "Leaky ReLU"), (softplus, "Softplus")
]

plt.title("Funciones de Activación x ∈ [-10, 10]")
plt.xlabel("Entrada (x)")
plt.ylabel("Salida (f(x))")
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.show()