# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dC70IOnzAAnh4GO5Dhh8k3Ybs44PIi-K
"""

import numpy as np
import tensorflow as tf

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import roc_auc_score, average_precision_score
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from tensorflow.keras.callbacks import CallbackList

print(tf.config.list_physical_devices())

#Para tener siempre una misma semilla de aleatoreidad
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

#Cargar el dataset
data = load_breast_cancer()
X = data.data.astype(np.float32)
Y = (data.target == 0).astype(np.int32)

#Division de mi dataset
#x=características
#y=etiqueta
X_train, X_temp, Y_train, Y_temp = train_test_split(
  X,Y,
  test_size=0.3,
  stratify=Y,
  random_state=SEED)

X_val, X_test, Y_val, Y_test = train_test_split(
  X_temp,Y_temp,
  test_size=0.5,
  stratify=Y_temp,
  random_state=SEED)

#Scaling
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_val_s = scaler.transform(X_val)
X_test_s = scaler.transform(X_test)

#Balance de las clases
classes = np.array([0, 1])
cw = compute_class_weight(class_weight='balanced', classes=classes, y=Y_train)
class_weight = {0: float(cw[0]), 1:float(cw[1])}

#Modelo de red neuronal
#Una epoca hace referencia a toda una vuelta a el dataset
# el dropout hace referencia a que en el entrenamiento se apagan cierto numero
#de neuronas aleatoriamente esto para que nuestra red neuronal evite aprenderse
#el data set
def build_model(input_dim):
  inputs =tf.keras.Input(shape=(input_dim,))
  x = tf.keras.layers.Dense(32, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-3))(inputs)
  x = tf.keras.layers.Dropout(0.25)(x)
  x = tf.keras.layers.Dense(16, activation='relu',  kernel_regularizer=tf.keras.regularizers.l2(1e-3))(x)
  x = tf.keras.layers.Dropout(0.20)(x)
  outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
  return tf.keras.Model(inputs, outputs)

model = build_model(X_train_s.shape[1])

#Metricas
metrics= [
    tf.keras.metrics.AUC(curve='ROC', name='Auc_ROC'),
    tf.keras.metrics.AUC(curve='PR', name='Auc_PR'),
    tf.keras.metrics.Recall(name='Recall'),
    tf.keras.metrics.Precision(name='Precision'),
]

#Compilar modelo
lr=1e-3
model.compile(
    optimizer=tf.keras.optimizers.Adam(lr),
    loss='binary_crossentropy',
    metrics=metrics
)

# CallBacks - EarlyStopping
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_Auc_ROC',
        mode='max',
        patience=20,
        restore_best_weights=True)
]

lr=1e-3
model.compile(
    optimizer=tf.keras.optimizers.Adam(lr),
    loss='binary_crossentropy',
    metrics=metrics
)
history = model.fit(
    X_train_s, Y_train,
    validation_data = (X_val_s, Y_val),
    epochs=300,
    batch_size=32,
    class_weight=class_weight,
    verbose=1,
    callbacks= callbacks
    summary=1

    )

# Graficacion
plt.figure()
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('PERDIDA')
plt.legend(['train', 'validation'])
plt.show()

